version: '2'
services:
    partenaire-app:
        image: partenaire
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://partenaire-mysql:3306/partenaire?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 4000:4000
    partenaire-mysql:
        extends:
            file: mysql.yml
            service: partenaire-mysql
